// <auto-generated />
using System.CodeDom.Compiler;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EcommerceApp.Web.Data.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260825230000_CurrentModelBaseline")]
[GeneratedCode("Microsoft.EntityFrameworkCore.Migrations", "10.0.0")]
partial class CurrentModelBaseline
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder) =>
        CurrentModelBaselineMetadata.BuildCurrentModel(modelBuilder);
}
