// <auto-generated />
using EcommerceApp.Web.Domain.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EcommerceApp.Web.Data.Migrations;

internal static class CurrentModelBaselineMetadata
{
    internal static void BuildCurrentModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "10.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);
        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity<IdentityRole>(b =>
        {
            b.Property<string>("Id").HasColumnType("text");
            b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().HasColumnType("text");
            b.Property<string>("Name").HasMaxLength(256).HasColumnType("character varying(256)");
            b.Property<string>("NormalizedName").HasMaxLength(256).HasColumnType("character varying(256)");
            b.HasKey("Id"); b.HasIndex("NormalizedName").IsUnique().HasDatabaseName("RoleNameIndex"); b.ToTable("AspNetRoles");
        });
        modelBuilder.Entity<IdentityRoleClaim<string>>(b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer").HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            b.Property<string>("ClaimType").HasColumnType("text"); b.Property<string>("ClaimValue").HasColumnType("text"); b.Property<string>("RoleId").IsRequired().HasColumnType("text");
            b.HasKey("Id"); b.HasIndex("RoleId"); b.ToTable("AspNetRoleClaims");
        });
        modelBuilder.Entity<ApplicationUser>(b =>
        {
            b.Property<string>("Id").HasColumnType("text"); b.Property<int>("AccessFailedCount").HasColumnType("integer"); b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().HasColumnType("text");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone"); b.Property<string>("DisplayName").IsRequired().HasColumnType("text");
            b.Property<string>("Email").HasMaxLength(256).HasColumnType("character varying(256)"); b.Property<bool>("EmailConfirmed").HasColumnType("boolean"); b.Property<bool>("LockoutEnabled").HasColumnType("boolean"); b.Property<DateTimeOffset?>("LockoutEnd").HasColumnType("timestamp with time zone");
            b.Property<string>("NormalizedEmail").HasMaxLength(256).HasColumnType("character varying(256)"); b.Property<string>("NormalizedUserName").HasMaxLength(256).HasColumnType("character varying(256)"); b.Property<string>("PasswordHash").HasColumnType("text"); b.Property<string>("PhoneNumber").HasColumnType("text"); b.Property<bool>("PhoneNumberConfirmed").HasColumnType("boolean"); b.Property<string>("SecurityStamp").HasColumnType("text"); b.Property<bool>("TwoFactorEnabled").HasColumnType("boolean"); b.Property<string>("UserName").HasMaxLength(256).HasColumnType("character varying(256)");
            b.HasKey("Id"); b.HasIndex("NormalizedEmail").HasDatabaseName("EmailIndex"); b.HasIndex("NormalizedUserName").IsUnique().HasDatabaseName("UserNameIndex"); b.ToTable("AspNetUsers");
        });
        modelBuilder.Entity<IdentityUserClaim<string>>(b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer").HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn); b.Property<string>("ClaimType").HasColumnType("text"); b.Property<string>("ClaimValue").HasColumnType("text"); b.Property<string>("UserId").IsRequired().HasColumnType("text");
            b.HasKey("Id"); b.HasIndex("UserId"); b.ToTable("AspNetUserClaims");
        });
        modelBuilder.Entity<IdentityUserLogin<string>>(b =>
        {
            b.Property<string>("LoginProvider").HasColumnType("text"); b.Property<string>("ProviderKey").HasColumnType("text"); b.Property<string>("ProviderDisplayName").HasColumnType("text"); b.Property<string>("UserId").IsRequired().HasColumnType("text");
            b.HasKey("LoginProvider", "ProviderKey"); b.HasIndex("UserId"); b.ToTable("AspNetUserLogins");
        });
        modelBuilder.Entity<IdentityUserRole<string>>(b =>
        {
            b.Property<string>("UserId").HasColumnType("text"); b.Property<string>("RoleId").HasColumnType("text"); b.HasKey("UserId", "RoleId"); b.HasIndex("RoleId"); b.ToTable("AspNetUserRoles");
        });
        modelBuilder.Entity<IdentityUserToken<string>>(b =>
        {
            b.Property<string>("UserId").HasColumnType("text"); b.Property<string>("LoginProvider").HasColumnType("text"); b.Property<string>("Name").HasColumnType("text"); b.Property<string>("Value").HasColumnType("text"); b.HasKey("UserId", "LoginProvider", "Name"); b.ToTable("AspNetUserTokens");
        });

        modelBuilder.Entity<Address>(b => { Id(b); b.Property<string>("UserId").IsRequired().HasColumnType("text"); Text(b,"Label",true); Text(b,"RecipientName",true); Text(b,"Line1",true); Text(b,"Line2"); Text(b,"City",true); Text(b,"Region",true); Text(b,"PostalCode",true); Text(b,"CountryCode",true); b.HasIndex("UserId"); b.ToTable("Addresses"); });
        modelBuilder.Entity<Category>(b => { Id(b); b.Property<string>("Name").IsRequired().HasMaxLength(80).HasColumnType("character varying(80)"); b.Property<string>("Slug").IsRequired().HasMaxLength(80).HasColumnType("character varying(80)"); Text(b,"Description",true); Text(b,"ImagePath",true); b.Property<int>("DisplayOrder").HasColumnType("integer"); b.Property<bool>("IsActive").HasColumnType("boolean"); b.HasIndex("Slug").IsUnique(); b.ToTable("Categories"); });
        modelBuilder.Entity<Product>(b => { Id(b); b.Property<int>("CategoryId").HasColumnType("integer"); Text(b,"Name",true); Text(b,"Slug",true); Text(b,"Sku",true); Text(b,"ShortDescription",true); Text(b,"Description",true); b.Property<decimal>("Price").HasPrecision(18,2).HasColumnType("numeric(18,2)"); b.Property<int>("StockQuantity").HasColumnType("integer"); Text(b,"ImagePath",true); Text(b,"SecondaryImagePath"); b.Property<bool>("IsFeatured").HasColumnType("boolean"); b.Property<bool>("IsActive").HasColumnType("boolean"); b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone"); b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone"); b.Property<long>("StockVersion").IsConcurrencyToken().HasColumnType("bigint"); b.HasIndex("CategoryId"); b.HasIndex("Slug").IsUnique(); b.HasIndex("Sku").IsUnique(); b.HasIndex("IsActive","CategoryId","Price"); b.ToTable("Products", t => { t.HasCheckConstraint("CK_Product_Price", "\"Price\" >= 0"); t.HasCheckConstraint("CK_Product_Stock", "\"StockQuantity\" >= 0"); }); });
        modelBuilder.Entity<Cart>(b => { b.Property<Guid>("Id").HasColumnType("uuid"); Text(b,"UserId"); Text(b,"SessionKey"); b.Property<string>("DiscountCode").HasMaxLength(64).HasColumnType("character varying(64)"); b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone"); b.HasKey("Id"); b.HasIndex("SessionKey").IsUnique(); b.HasIndex("UserId").IsUnique(); b.ToTable("Carts"); });
        modelBuilder.Entity<CartItem>(b => { Id(b); b.Property<Guid>("CartId").HasColumnType("uuid"); b.Property<int>("ProductId").HasColumnType("integer"); b.Property<int>("Quantity").HasColumnType("integer"); b.HasIndex("CartId","ProductId").IsUnique(); b.HasIndex("ProductId"); b.ToTable("CartItems", t => t.HasCheckConstraint("CK_CartItem_Quantity", "\"Quantity\" > 0")); });
        modelBuilder.Entity<DiscountCode>(b => { Id(b); Text(b,"Code",true); b.Property<string>("NormalizedCode").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)"); b.Property<DiscountKind>("Kind").HasColumnType("integer"); b.Property<decimal>("Value").HasPrecision(18,2).HasColumnType("numeric(18,2)"); b.Property<decimal>("MinimumSubtotal").HasPrecision(18,2).HasColumnType("numeric(18,2)"); b.Property<decimal?>("MaximumDiscount").HasPrecision(18,2).HasColumnType("numeric(18,2)"); b.Property<DateTimeOffset>("StartsAt").HasColumnType("timestamp with time zone"); b.Property<DateTimeOffset>("EndsAt").HasColumnType("timestamp with time zone"); b.Property<bool>("IsActive").HasColumnType("boolean"); b.Property<int?>("UsageLimit").HasColumnType("integer"); b.HasIndex("NormalizedCode").IsUnique(); b.ToTable("DiscountCodes", t => { t.HasCheckConstraint("CK_DiscountCode_Value", "\"Value\" > 0"); t.HasCheckConstraint("CK_DiscountCode_Window", "\"EndsAt\" > \"StartsAt\""); t.HasCheckConstraint("CK_DiscountCode_UsageLimit", "\"UsageLimit\" IS NULL OR \"UsageLimit\" > 0"); }); });
        modelBuilder.Entity<DiscountRedemption>(b => { Id(b); b.Property<int>("DiscountCodeId").HasColumnType("integer"); b.Property<int>("OrderId").HasColumnType("integer"); Text(b,"UserId"); b.Property<DateTimeOffset>("RedeemedAt").HasColumnType("timestamp with time zone"); b.HasIndex("DiscountCodeId"); b.HasIndex("OrderId"); b.ToTable("DiscountRedemptions"); });
        modelBuilder.Entity<Order>(b => { Id(b); Text(b,"OrderNumber",true); Text(b,"CheckoutToken",true); Text(b,"ConfirmationToken",true); Text(b,"CustomerId"); Text(b,"ContactEmail",true); Text(b,"RecipientName",true); Text(b,"ShippingAddress",true); Money(b,"Subtotal"); Money(b,"DiscountTotal"); Money(b,"ShippingTotal"); Money(b,"Total"); Text(b,"DiscountCodeSnapshot"); b.Property<OrderStatus>("Status").HasColumnType("integer"); b.Property<PaymentStatus>("PaymentStatus").HasColumnType("integer"); b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone"); b.HasIndex("OrderNumber").IsUnique(); b.HasIndex("CheckoutToken").IsUnique(); b.HasIndex("ConfirmationToken").IsUnique(); b.HasIndex("CustomerId","CreatedAt"); b.HasIndex("Status","CreatedAt"); b.ToTable("Orders"); });
        modelBuilder.Entity<OrderItem>(b => { Id(b); b.Property<int>("OrderId").HasColumnType("integer"); b.Property<int?>("ProductId").HasColumnType("integer"); Text(b,"Sku",true); Text(b,"ProductName",true); Money(b,"UnitPrice"); b.Property<int>("Quantity").HasColumnType("integer"); b.HasIndex("OrderId"); b.HasIndex("ProductId"); b.ToTable("OrderItems", t => t.HasCheckConstraint("CK_OrderItem_Quantity", "\"Quantity\" > 0")); });

        modelBuilder.Entity<IdentityRoleClaim<string>>().HasOne<IdentityRole>().WithMany().HasForeignKey("RoleId").OnDelete(DeleteBehavior.Cascade).IsRequired();
        modelBuilder.Entity<IdentityUserClaim<string>>().HasOne<ApplicationUser>().WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
        modelBuilder.Entity<IdentityUserLogin<string>>().HasOne<ApplicationUser>().WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
        modelBuilder.Entity<IdentityUserRole<string>>().HasOne<IdentityRole>().WithMany().HasForeignKey("RoleId").OnDelete(DeleteBehavior.Cascade).IsRequired();
        modelBuilder.Entity<IdentityUserRole<string>>().HasOne<ApplicationUser>().WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
        modelBuilder.Entity<IdentityUserToken<string>>().HasOne<ApplicationUser>().WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
        modelBuilder.Entity<Address>().HasOne(x => x.User).WithMany(x => x.Addresses).HasForeignKey(x => x.UserId).OnDelete(DeleteBehavior.Cascade).IsRequired();
        modelBuilder.Entity<Product>().HasOne(x => x.Category).WithMany(x => x.Products).HasForeignKey(x => x.CategoryId).OnDelete(DeleteBehavior.Restrict).IsRequired();
        modelBuilder.Entity<Cart>().HasOne(x => x.User).WithMany().HasForeignKey(x => x.UserId);
        modelBuilder.Entity<CartItem>().HasOne(x => x.Cart).WithMany(x => x.Items).HasForeignKey(x => x.CartId).OnDelete(DeleteBehavior.Cascade).IsRequired();
        modelBuilder.Entity<CartItem>().HasOne(x => x.Product).WithMany().HasForeignKey(x => x.ProductId).OnDelete(DeleteBehavior.Cascade).IsRequired();
        modelBuilder.Entity<DiscountRedemption>().HasOne(x => x.DiscountCode).WithMany(x => x.Redemptions).HasForeignKey(x => x.DiscountCodeId).OnDelete(DeleteBehavior.Cascade).IsRequired();
        modelBuilder.Entity<DiscountRedemption>().HasOne(x => x.Order).WithMany().HasForeignKey(x => x.OrderId).OnDelete(DeleteBehavior.Cascade).IsRequired();
        modelBuilder.Entity<Order>().HasOne(x => x.Customer).WithMany().HasForeignKey(x => x.CustomerId);
        modelBuilder.Entity<OrderItem>().HasOne(x => x.Order).WithMany(x => x.Items).HasForeignKey(x => x.OrderId).OnDelete(DeleteBehavior.Cascade).IsRequired();
        modelBuilder.Entity<OrderItem>().HasOne(x => x.Product).WithMany().HasForeignKey(x => x.ProductId).OnDelete(DeleteBehavior.SetNull);
#pragma warning restore 612, 618
    }

    private static void Id<TEntity>(EntityTypeBuilder<TEntity> b) where TEntity : class { b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer").HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn); b.HasKey("Id"); }
    private static void Text<TEntity>(EntityTypeBuilder<TEntity> b, string name, bool required = false) where TEntity : class { var p = b.Property<string>(name).HasColumnType("text"); if (required) p.IsRequired(); }
    private static void Money<TEntity>(EntityTypeBuilder<TEntity> b, string name) where TEntity : class => b.Property<decimal>(name).HasPrecision(18, 2).HasColumnType("numeric(18,2)");
}
